ProyectoFinal/AppCoder/urls.py
from django.urls import path
from . import views


app_name = 'productos'

urlpatterns = [
    path('', views.home, name='index'),
    path('productos/', views.consultar, name="consultar"),
    path('guardar/', views.guardar, name="guardar"),   
    #ruta/id de tabla
    path('eliminar/<int:id>/', views.eliminar, name='eliminar'),
    path('detalle/<int:id>', views.detalle, name='detalle'),

]

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppCoder.urls')), 
    ]

ProyectoFinal/AppCoder/models.py
from django.db import models


# Create your models here.
  

class Producto(models.Model):
    nombre = models.CharField(max_length=30, unique=True)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return self.nombre + ", $" + str(self.precio) + ", " + self.descripcion

ProyectoFinal/AppCoder/forms.py
from django import forms


class ProductoFormulario(forms.Form):
    nombre = forms.CharField(max_length=50)
    cantidad = forms.IntegerField()

class ProductoBusqueda(forms.Form):
    nombre = forms.CharField(max_length=50)

ProyectoFinal/AppCoder/views.py
from django.shortcuts import render, redirect
from .models import Producto
from django.contrib import messages

def home(request):
    return render(request, "AppCoder/padre.html") 

def consultar(request):
    #variable = tabla.objetos.todos
    productos  = Producto.objects.all()
    return render(request, "AppCoder/productos.html",{
        'productos ': productos ,
    })

def guardar(request):
    #name en producto.html
    nombre = request.POST["nombre"]
    precio = request.POST["precio"]
    descripcion = request.POST["descripcion"]
    #nueva variable = Modelo(izquierda, nombre en models.variable a la que hacemos referencia)
    p = Producto(nombre=nombre, precio=precio, descripcion=descripcion)
    #guardar datos 
    p.save()
    messages.success(request, 'Producto guardado correctamente')
    #redireccionar a otra pagina
    return redirect('productos:consultar')

def eliminar(request, id):
    #ir por el producto
    #variable = tabla.objetos.filtro
    producto  = Producto.objects.get(pk=id)
    producto .delete()
    messages.success(request, 'Producto eliminado correctamente')
    #redireccionar a otra pagina
    return redirect('productos:consultar')

def detalle(request, id):
    productos = Producto.objects.get(pk=id)
    return render(request, "AppCoder/productoEditar.html", {
        'productos'  : productos 
        })

ProyectoFinal/AppCoder/templates/AppCoder/index.html
{% extends 'AppCoder/padre.html' %}

{% block content %}
    <h1 class="text-center">Estas en: INDEX</h1>
{% endblock content %}

ProyectoFinal/AppCoder/templates/AppCoder/padre.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PADRE</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
     
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'productos:index' %}">INICIO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'productos:consultar' %}">Ver productos |</a>
                    <a class="nav-link active" aria-current="page" href="!#">Editar productos |</a>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock content %}
</body>

</html>

ProyectoFinal/AppCoder/templates/AppCoder/productoEditar.html
editar{% extends 'AppCoder/padre.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success">{{message}}</div>
{% endfor %}
{% endif %}

<h2 class="text-center">EDITAR</h2>

<form class="w-50 shadow mx-auto p-4 m-3" method="post" action={% url 'productos:guardar' %}>

    {% csrf_token %}
    Nombre: <input type="text" name="nombre" class="form-control" required  {{producto.nombre}}>
    <br>
    Precio: <input type="number" name="precio" class="form-control" required {{producto.precio }}>
    <br>
    Descripcion:
    <textarea class="form-control my-2" name="descripcion">{{producto.descripcion}}

    </textarea>
    <br>

    <input type="submit" value="Actualizar" class="btn btn-primary">Actualizar
</form>
{% endblock content %}

ProyectoFinal/AppCoder/templates/AppCoder/productos.html
{% extends 'AppCoder/padre.html' %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success">{{message}}</div>
{% endfor %}
{% endif %}

<h2 class="text-center">PRODUCTOS</h2>

<form class="w-50 shadow mx-auto p-4 m-3" method="post" action={% url 'productos:guardar' %}>

    {% csrf_token %}
    Nombre: <input type="text" name="nombre" class="form-control" required>
    <br>
    Precio: <input type="number" name="precio" class="form-control" required>
    <br>
    Descripcion:
    <textarea class="form-control my-2" name="descripcion">
    </textarea>
    <br>
    <input type="submit" value="Guardar" class="btn btn-primary">
</form>

    


    <table class="table table-info w-75 mx-auto text-center">
        <tr class="table-dark">
            <th>Nombre</th>
            <th>Precio</th>
            <th>Descripcion</th>
            <th colspan="2"></th>
        </tr>

        {% for producto in productos %}
        <tr>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.precio }}</td>
            <td>{{ producto.descripcion }}</td>
            <td>
                <form action="{% url 'productos:eliminar'  producto_id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" onclick="return confirm ('Eliminar el producto seleccionado?')">Eliminar
                    </button>
                </form>
            </td>
        </tr>
            <td>
                <form action="{% url 'productos:detalle' producto_id %}" method="get">
                    {% csrf_token %}
                    <button class="btn btn-warning" onclick="return confirm ('Editar el producto seleccionado?')">Editar
                    </button>
                </form>
            </td>
        {% endfor %}
    </table>
{% endblock content %}